class ListDefaultSets {
  final int defaultMaxCards;

  ListDefaultSets(this.defaultMaxCards);

  List<Map<String, dynamic>> get defaultValue {
    return [
      {
        'name': "Motivational Quotes (Template)",
        'timestamp': DateTime.now(),
        'description': "A collection of quotes to inspire and uplift.",
        'cards': [
          {'isUpdating': false, 'question': "What is your favorite motivational quote?", 'answer': "The only way to do great work is to love what you do. - Steve Jobs", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Who is someone you look up to for inspiration?", 'answer': "Elon Musk", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What helps you stay positive during hard times?", 'answer': "Remembering my goals and past achievements.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What does success mean to you?", 'answer': "Achieving your personal goals.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is your biggest source of motivation?", 'answer': "My family and dreams.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "How do you stay motivated when you feel like quitting?", 'answer': "I remind myself why I started.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s the best piece of advice you’ve received?", 'answer': "Stay consistent and patient.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Who do you turn to for inspiration?", 'answer': "Books and mentors.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What motivates you to improve each day?", 'answer': "The desire to be a better version of myself.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What would you do if money wasn’t an issue?", 'answer': "Travel the world and explore new cultures.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What does a productive day look like for you?", 'answer': "Finishing tasks with quality and making progress towards my goals.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is your biggest fear about achieving your goals?", 'answer': "That I’ll lose sight of what truly matters.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What would you say is your greatest strength?", 'answer': "My resilience and determination.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "How do you handle criticism?", 'answer': "I use it to grow and improve.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What drives you to work hard?", 'answer': "The desire to create something meaningful.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "How do you celebrate small victories?", 'answer': "By taking a moment to reflect and reward myself.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What book has inspired you the most?", 'answer': "The 7 Habits of Highly Effective People.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "How do you stay focused?", 'answer': "By breaking down tasks and setting clear priorities.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What are the key habits of successful people?", 'answer': "Consistency, determination, and time management.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the biggest obstacle you’ve overcome?", 'answer': "Overcoming self-doubt and fear of failure.", 'isIgnore': false, 'timestamp': DateTime.now()},
        ],
        'numberOfQuiz': 20,
        'limitNumberOfQuiz': defaultMaxCards,
      },
      {
        'name': "Travel Destinations (Template)",
        'timestamp': DateTime.now(),
        'description': "Explore top travel destinations around the world.",
        'cards': [
          {'isUpdating': false, 'question': "Which city do you most want to visit?", 'answer': "Paris, France", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What type of travel do you prefer—adventure, relaxation, or culture?", 'answer': "Adventure", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is your favorite travel memory?", 'answer': "Seeing the Northern Lights in Iceland.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Where would you like to go on a road trip?", 'answer': "The Pacific Coast Highway in the USA.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s your dream vacation?", 'answer': "A month-long stay in Japan, exploring culture and food.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What destination is at the top of your bucket list?", 'answer': "New Zealand", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Do you prefer staying in a hotel or Airbnb?", 'answer': "Airbnb for a more local experience.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the best travel tip you've ever received?", 'answer': "Pack light and leave room for souvenirs!", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What type of vacation do you prefer?", 'answer': "Beach relaxation.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s the most unique place you’ve ever visited?", 'answer': "The Sahara Desert.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What do you look for in a great travel destination?", 'answer': "Beautiful landscapes and cultural experiences.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Do you like to travel solo or with a group?", 'answer': "Solo for self-discovery.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s your favorite travel activity?", 'answer': "Hiking and nature walks.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s the best time of year to travel?", 'answer': "Spring, for perfect weather and fewer crowds.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Where would you want to travel to experience a different culture?", 'answer': "India.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What type of food do you look forward to when traveling?", 'answer': "Street food and local delicacies.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s the most amazing natural wonder you’ve seen?", 'answer': "The Grand Canyon.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What city would you visit for a cultural experience?", 'answer': "Rome, Italy.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s your favorite mode of transportation when traveling?", 'answer': "Trains for scenic views and comfort.", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What’s the longest trip you’ve taken?", 'answer': "A 2-month backpacking journey through Southeast Asia.", 'isIgnore': false, 'timestamp': DateTime.now()},
        ],
        'numberOfQuiz': 20,
        'limitNumberOfQuiz': defaultMaxCards,
      },
      {
        'name': "General Knowledge (Template)",
        'timestamp': DateTime.now(),
        'description': "A variety of questions to test your general knowledge.",
        'cards': [
          {'isUpdating': false, 'question': "What is the capital of Australia?", 'answer': "Canberra", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Who developed the theory of relativity?", 'answer': "Albert Einstein", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the largest mammal in the world?", 'answer': "Blue Whale", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the smallest country in the world?", 'answer': "Vatican City", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Who wrote the play Romeo and Juliet?", 'answer': "William Shakespeare", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the longest river in the world?", 'answer': "The Nile", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What planet is known as the Red Planet?", 'answer': "Mars", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the largest island in the world?", 'answer': "Greenland", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "Who was the first person to step on the moon?", 'answer': "Neil Armstrong", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the currency of Japan?", 'answer': "Yen", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the tallest mountain in the world?", 'answer': "Mount Everest", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What year did World War II end?", 'answer': "1945", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the longest running TV show?", 'answer': "The Simpsons", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the capital of France?", 'answer': "Paris", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the chemical symbol for gold?", 'answer': "Au", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the largest ocean in the world?", 'answer': "Pacific Ocean", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the hardest rock in the world?", 'answer': "Diamond", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the smallest bone in the human body?", 'answer': "Stapes", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the currency  of Japan?", 'answer': "Yen", 'isIgnore': false, 'timestamp': DateTime.now()},
          {'isUpdating': false, 'question': "What is the tallest  mountain in the world?", 'answer': "Mount Everest", 'isIgnore': false, 'timestamp': DateTime.now()},
        ],
        'numberOfQuiz': 20,
        'limitNumberOfQuiz': defaultMaxCards,
      },
    ];
  }
}
