name: flashi
description: "Offline-first flashcard and quiz maker"
publish_to: 'none'
version: 2.0.0+13

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  sqflite: 2.4.2
  path: 1.9.1
  path_provider: 2.1.5
  uuid: 4.5.1
  crypto: 3.0.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  http: 1.6.0
  file_picker: 8.1.7
  image_picker: 1.1.2
  share_plus: 10.1.4
  flutter_secure_storage: 9.2.4
  google_sign_in: 6.2.2
  startapp_sdk: 1.0.1
  package_info_plus: 8.2.1
  url_launcher: 6.3.1
  flutter_tts: 3.8.5
  flip_card: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: 2.3.6
  flutter_launcher_icons: 0.14.3
  flutter_lints: 5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - asset/font/Montserrat-Regular.ttf
    - asset/font/Montserrat-Bold.ttf
    - asset/icon/icon.png
    - asset/images/onboarding_1.png
    - asset/images/onboarding_2.png
    - asset/images/onboarding_3.jpg
    - asset/images/onboarding_4.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/font/Montserrat-Regular.ttf
        - asset: asset/font/Montserrat-Bold.ttf
          weight: 500
